title: 'MÖRK BORG Wiki'
description: 'A Fan-made Wiki of a Dying World'
baseurl: '/mork-borg-wiki'
url: 'https://trevor-ryan-burkholder.github.io'

# Build settings
markdown: kramdown
theme: null

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Collections (none needed — flat pages)
# GitHub Pages safe mode
plugins: []

